### PR TITLE
featured_src is not read-only in current released API version

### PR DESCRIPTION
**Pull request by theinventor**
In our testing we noticed we are able to use this field, and it's the correct way to set a featured image at this time.

Am I putting this in the right place?

### CODE REVIEW

**Comment by claudiosmweb** [comment]
@theinventor I'll check it later. thanks.

**Comment by claudiosmweb** [comment]
I just checked, for v2 is `read-only`.

**Comment by theinventor** [comment]
@claudiosmweb is current woocommerce versioned 2.5 using the v2 api or the v3?

In the current live version we are able to set this field. 

The documentation is wrong

**Comment by claudiosmweb** [comment]
It's `read-only` on v2 and v3 using WooCommerce 2.5.

See by yourself:

https://github.com/woothemes/woocommerce/blob/master/includes/api/class-wc-api-products.php#L1146

Only in one place it is possible to find `featured_src`... And where we are seeing is just the view/read context.

**Comment by claudiosmweb** [comment]
> In the current live version we are able to set this field. 

Show me how.

**Comment by theinventor** [comment]
@claudiosmweb Ok, what we saw is when we apply a bunch of images - there is no featured image. When we set that field, a featured image is there.

I don't actually care enough to burden myself further - I was just trying to be helpful in pointing this out.

**Pull request closed without merging**
